### ISSUE TITLE
Interface for specifying ports

### ISSUE THREAD

**Issue by mic-pan** [jedforrest/BondGraphs.jl#59]
The current interface for specifying ports is a bit unintuitive. I often find myself using helper functions to make my code easier to follow. See below for an example.

```
function pconnect!(model,t1,t2)
    (c1,p1) = port_info(t1)
    (c2,p2) = port_info(t2)
    connect!(model,c1,c2,srcportindex=p1,dstportindex=p2)
end
port_info(t::AbstractNode) = (t,BondGraphs.nextfreeport(t))
port_info(t::Tuple) = t
```

**Comment by jedforrest** [comment]
Should be fixed with #66 

The new syntax is similar to your helper function where nodes can optionally be provided with a port index or label.
```julia
# All valid syntax assuming dst has 2 ports
connect!(model, src,  dst)
connect!(model, src, (dst, 2))
connect!(model, (src, 1), (dst, 2))
```
