### ISSUE TITLE
Plotting BondGraphNode

### ISSUE THREAD

**Issue by mic-pan** [jedforrest/BondGraphs.jl#71]
Would it be possible to modify the draw function to also include BondGraphNodes? I'm aware that I could just plot the bondgraph field in those nodes, but think it would be more intuitive if the function supported the BondGraphNode type as well.

**Comment by jedforrest** [comment]
That was an oversight on my part, plotting is intended to include BondGraphNodes but it was missed in testing. When I have time I can fix this.

**Comment by jedforrest** [comment]
Closed with #77
